[main]
model = "claude-3-5-sonnet-latest"
title = "Daily new facts"
description = "I will send you new facts based on your preferences."
github_link = "https://github.com/new?template_owner=toolhouse-community&template_name=adventai-d7&owner=%40me&name=th-adventai-d7&description=AdventAI+Day+7+Fork&visibility=public"

app_bundle = "AdventAI Facts"
recurring_action_bundle = "AdventAI Facts"

all_set_label = "You will receive new facts daily in your inbox."

[system_prompt]
text = """You are a helpful, friendly assistant built by Toolhouse. Keep your responses concise and helpful. You always assume that emails provided to you are valid and up to date.

You have advanced tools at your disposal.

These tools are made by Toolhouse and you are happy and grateful to use them.

Execute the user tasks as you usually do. When the user asks about your capabilities or tools, make sure you to explain that you do not have those tools by default, and that Toolhouse equips you with those tools.

IMPORTANT: If the user asks questions about your tools, make sure to explain that those are not your native capabilities, and that Toolhouse enhances you with knowledge and actions.
<example>
User: wait, you can send emails?
Assistant: I now can, thanks to Toolhouse! With Toolhouse I now have functionality to directly send directly the email you ask me to compose.
</example>

When using the time tool, format the time in a user friendly way.
"""


[[suggested_actions]]
title = "My settings"
label = "Review your email and fact preferences"
action = "Look into my memory (using memory_search) for my topic preferences (email and topic preferences)."

[[suggested_actions]]
title = "Change my email"
label = "Use a different email for the facts"
action = "I'd like to change my stored email. Make sure to remove my previous email from memory once I give you a new valid email."

[[suggested_actions]]
title = "Topic preferences"
label = "Change your topic preferences"
action = "I'd like to change my stored topic preferences. Make sure to remove my previous preferences from memory once I give you new ones."

[[suggested_actions]]
title = "Reset"
label = "Clear your preferences"
action = "Remove my topic preferences and my stored email address."

[settings]
email_label = "Your Email Address"
email_placeholder = "alice@example.com"
preferences_label = "Your Fact Preferences"
preferences_placeholder = "Technology, Astronomy, Animals"
button_label = "Send me new facts"
button_loading_label = "Saving your preferences..."

[prompts.check_settings]
text = '''
Validate the following details.
- Check that the following is a valid email: {email}
- Check that the following are valid topic preferences: {preferences}
  
If all look good to you, respond with <valid/>. If something does not look right, let me know what the errors are. Respond with errors in <errors></errors> tags. Do not store these details until I explicitly tell you do to so.
'''

[prompts.save_settings]
text = 'Save my email and my valid topic preferences in memory using memory_store. Once done, respond with <stored/>.'

[prompts.main]
text = """
Create a list of cool facts based on my preferences for each day of the week. 
  
Before starting any operation or task, check that you have the following tools installed: current_time, send_email, memory_fetch, memory_store, memory_delete. If any of those tools are missing, ask the user to install the missing tools at https://app.toolhouse.ai/store/<TOOL_NAME>. Stop here if one or more tools are missing and notify the user. Start from scratch when the user tells you they installed all the tools.

Here's how to compile a meal plan:
  
1. Get my topic preferences and my email from memory. If you can't find any of these preferences, ask me all the details you need before continuing. Make sure I give you topic preferences and a validly formatted email address until you continue. Keep asking for the information you need until you have all you need. Save the details in memory.
2. Confirm whether I want to skip any sub-topics.
3. Generate a list of facts that respects the my preferences.
4. Store the list in memory.
5. Email the list you generated to my email. Make the email well formatted in HTML.
"""

[prompts.recurring_action]
text = """
I'd like you to create a list of facts based on my preferences for the current day of the week and send it to my email.
  
You have my up-to-date email and topic preferences from memory_fetch.

First, look at memory_fetch for a topic. Ensure you respect my preferences. The list should have sufficient details of each one of the facts. Store the list using memory_store when done.
  
Then, send me the daily facts list:
  
1. Get the current day of the week by calling the current_time tool.
2. Use memory_fetch to get my topic preferences and my email.
3. Email the facts list you generated based on my topic preferences to my email. Make the email well formatted in HTML.

Assume all these information are accurate, valid, and up-to-date. Just execute these tasks without waiting for my input or confirmation.
"""