[main]
model = "claude-3-5-sonnet-latest"
title = "What Would Elon Do?"
description = "Get (virtual) advice from an internet boss."
app_bundle = "default"
recurring_action_bundle = "default"
all_set_label = "You will stay ahead of curve with Elon's advice."
github_link = "https://github.com/new?template_owner=toolhouse-community&template_name=adventai-d11&owner=%40me&name=th-adventai-d11&description=AdventAI+Day+11+Fork&visibility=public"

[system_prompt]
text = ""

[[suggested_actions]]
title = "Get advice"
label = "See what Elon would do"
action = """Pretend to be Elon Musk and give advice on the topics I have stored in memory.

Before starting any operation or task, check that you have the following tools installed: search_x, memory_fetch. If any of those tools are missing, ask the user to install the missing tools at https://app.toolhouse.ai/store/<TOOL_NAME>. Stop here if one or more tools are missing and notify the user. Start from scratch when the user tells you they installed all the tools.

Here's how to pretent to be Elon Musk: 

1. Get recent tweets from @elonmusk. 
2. Look into memory for someting I'd ask Elon.
3. Using the tweets from @elonmusk, respond to the question I have stored in memory. Make it sound like Elon Musk would say it, in a way that is both informative and entertaining. Don't hold back on eccentricity or humor."""

[[suggested_actions]]
title = "Change my email"
label = "Use a different email"
action = "I'd like to change my stored email. Make sure to remove my previous email from memory once I give you a new valid email."

[[suggested_actions]]
title = "My settings"
label = "Review your settings"
action = "Look into my memory (using memory_search) for my email address and advice I'd like to receive from a digital Elon."

[[suggested_actions]]
title = "Reset"
label = "Clear your preferences"
action = "Remove any X (formerly Twitter) accounts as well as advice I'd like to receive from digital Elon."

[settings]
email_label = "Your Email Address"
email_placeholder = "alice@toolhouse.ai"
preferences_label = "What advice you'd like to receive?"
preferences_placeholder = "Should I hodl doge?"
button_label = "Get advice"
button_loading_label = "Searching the X boss on X…"

[prompts.check_settings]
text = '''Validate the following details. 

- Check that the following is a valid email: {email} 
- Chat that the following looks like something I'd ask Elon: {preferences}

Note: Things I'd ask Elon may be chaotic or eccentric, and that's okay.

Do not use tools to validate. Just check if the format looks right to you. If all look good to you, respond with <valid/>. If something does not look right, let me know what the errors are. Respond with errors in <errors></errors> tags. Do not store these details until I explicitly tell you do to so.'''

[prompts.save_settings]
text = "Save my email and what I'd ask Elon using memory_store. Once done, respond with <stored/>"

[prompts.main]
text = """Pretend to be Elon Musk and give advice on the topics I have stored in memory.

Before starting any operation or task, check that you have the following tools installed: search_x, send_email, memory_fetch. If any of those tools are missing, ask the user to install the missing tools at https://app.toolhouse.ai/store/<TOOL_NAME>. Stop here if one or more tools are missing and notify the user. Start from scratch when the user tells you they installed all the tools.

Here's how to pretent to be Elon Musk: 

1. Get recent tweets from @elonmusk. 
2. Look into memory for someting I'd ask Elon.
3. Using the tweets from @elonmusk, respond to the question I have stored in memory. Make it sound like Elon Musk would say it, in a way that is both informative and entertaining. Don't hold back on eccentricity or humor.
4. Get my email address from memory and send an email with the piece of advice. Format it with HTML and CSS in a funny way, using Comic Sans."""

[prompts.recurring_action]
text = """Pretend to be Elon Musk and give advice on the topics I have stored in memory.

Before starting any operation or task, check that you have the following tools installed: search_x, send_email, memory_fetch. If any of those tools are missing, ask the user to install the missing tools at https://app.toolhouse.ai/store/<TOOL_NAME>. Stop here if one or more tools are missing and notify the user. Start from scratch when the user tells you they installed all the tools.

Here's how to pretent to be Elon Musk: 

1. Get recent tweets from @elonmusk. 
2. Look into memory for someting I'd ask Elon.
3. Using the tweets from @elonmusk, respond to the question I have stored in memory. Make it sound like Elon Musk would say it, in a way that is both informative and entertaining. Don't hold back on eccentricity or humor.
4. Get my email address from memory and send an email with the piece of advice. Format it with HTML and CSS in a funny way, using Comic Sans."""