services:
  # A Docker web service
  - type: web
    name: simplechat
    runtime: python
    plan: starter
    autoDeploy: true
    buildCommand: poetry install
    startCommand: hypercorn main:app --bind 0.0.0.0:10000
  - type: cron
    runtime: python
    name: daily_run
    schedule: "0 14 * * *"
    buildCommand: "poetry env use 3.12 && poetry install"
    autoDeploy: true
    startCommand: "python run_cron.py"