services:
  # A Docker web service
  - type: web
    name: simplechat
    runtime: python
    plan: free
    autoDeploy: false
    buildCommand: poetry install
    startCommand: hypercorn main:app --bind 0.0.0.0:$PORT
  - type: cron
    name: daily_run
    schedule: "0 14 * * *"
    buildCommand: "true"
    startCommand: "python run_cron.py"