services:
  # A Docker web service
  - type: web
    name: simplechat
    runtime: python
    plan: free
    autoDeploy: false
    buildCommand: poetry install
    startCommand: hypercorn main:app --bind 0.0.0.0:$PORT